/**
 * Embedded curated index (fallback when the remote plaza.json is unreachable).
 * Generated from skill-plaza/plaza.json — keep in sync via scripts/gen-plaza.ts.
 */
export interface CuratedSkill {
  readonly id: string
  readonly name: string
  readonly nameZh?: string
  readonly description: string
  readonly descriptionZh?: string
  readonly repo: string
  readonly path: string
  readonly ref: string
}

export const CURATED_FALLBACK: readonly CuratedSkill[] = [
  { id: 'algorithmic-art', name: 'algorithmic-art', nameZh: '算法艺术', description: "Creating algorithmic art using p5.js with seeded randomness and interactive parameter exploration. Use this when users request creating art using code, generative art, algorithmic art, flow fields, or particle systems. Create original algorithmic art rather than copying existing artists' work to avoid copyright violations.", descriptionZh: '使用 p5.js 创作算法艺术：种子随机性 + 交互式参数探索。用户要求用代码创作艺术、生成式艺术、流场或粒子系统时使用；只创作原创作品，避免版权问题。', repo: 'anthropics/skills', path: 'skills/algorithmic-art', ref: 'main' },
  { id: 'brand-guidelines', name: 'brand-guidelines', nameZh: '品牌规范应用', description: "Applies Anthropic's official brand colors and typography to any sort of artifact that may benefit from having Anthropic's look-and-feel. Use it when brand colors or style guidelines, visual formatting, or company design standards apply.", descriptionZh: '为任何作品套用官方品牌配色与字体规范，需要品牌色、视觉格式或公司设计标准时使用。', repo: 'anthropics/skills', path: 'skills/brand-guidelines', ref: 'main' },
  { id: 'canvas-design', name: 'canvas-design', nameZh: '画布视觉设计', description: "Create beautiful visual art in .png and .pdf documents using design philosophy. You should use this skill when the user asks to create a poster, piece of art, design, or other static piece. Create original visual designs, never copying existing artists' work to avoid copyright violations.", descriptionZh: '运用设计哲学在 .png 与 .pdf 文档中创作海报、艺术作品、设计稿等静态视觉作品；坚持原创设计，不抄袭他人作品。', repo: 'anthropics/skills', path: 'skills/canvas-design', ref: 'main' },
  { id: 'claude-api', name: 'claude-api', nameZh: 'Claude API 开发', description: '|-', descriptionZh: '基于 Claude API 构建应用：消息对话、工具调用、流式输出与最佳实践。', repo: 'anthropics/skills', path: 'skills/claude-api', ref: 'main' },
  { id: 'doc-coauthoring', name: 'doc-coauthoring', nameZh: '文档协作撰写', description: 'Guide users through a structured workflow for co-authoring documentation. Use when user wants to write documentation, proposals, technical specs, decision docs, or similar structured content. This workflow helps users efficiently transfer context, refine content through iteration, and verify the doc works for readers. Trigger when user mentions writing docs, creating proposals, drafting specs, or similar documentation tasks.', descriptionZh: '通过结构化流程引导协作撰写文档、方案、技术规格、决策文档等结构化内容：高效传递上下文、迭代打磨、验证可读性。', repo: 'anthropics/skills', path: 'skills/doc-coauthoring', ref: 'main' },
  { id: 'docx', name: 'docx', nameZh: 'Word 文档处理', description: "Use this skill whenever the user wants to create, read, edit, or manipulate Word documents (.docx files) or Word templates (.dotx files). Triggers include: any mention of 'Word doc', 'word document', '.docx', '.dotx', or requests to produce professional documents with formatting like tables of contents, headings, page numbers, or letterheads. Also use when extracting or reorganizing content from .docx or .dotx files, inserting or replacing images in documents, performing find-and-replace in Word files, working with tracked changes or comments, or converting content into a polished Word document. If the user asks for a 'report', 'memo', 'letter', 'template', or similar deliverable as a Word or .docx file, use this skill. Do NOT use for PDFs, spreadsheets, Google Docs, or general coding tasks unrelated to document generation.", descriptionZh: '创建、读取、编辑、操作 Word 文档（.docx/.dotx）：目录、标题、页码、页眉、插入替换图片、查找替换、修订与批注。', repo: 'anthropics/skills', path: 'skills/docx', ref: 'main' },
  { id: 'frontend-design', name: 'frontend-design', nameZh: '前端设计', description: "Guidance for distinctive, intentional visual design when building new UI or reshaping an existing one. Helps with aesthetic direction, typography, and making choices that don't read as templated defaults.", descriptionZh: '构建或重塑界面时的视觉设计指导：美学方向、排版，避免模板化的默认设计。', repo: 'anthropics/skills', path: 'skills/frontend-design', ref: 'main' },
  { id: 'internal-comms', name: 'internal-comms', nameZh: '内部沟通写作', description: 'A set of resources to help me write all kinds of internal communications, using the formats that my company likes to use. Claude should use this skill whenever asked to write some sort of internal communications (status reports, leadership updates, 3P updates, company newsletters, FAQs, incident reports, project updates, etc.).', descriptionZh: '按公司统一格式撰写内部沟通文案：状态报告、领导更新、公司简报、FAQ、事故报告、项目更新等。', repo: 'anthropics/skills', path: 'skills/internal-comms', ref: 'main' },
  { id: 'mcp-builder', name: 'mcp-builder', nameZh: 'MCP 服务构建', description: 'Guide for creating high-quality MCP (Model Context Protocol) servers that enable LLMs to interact with external services through well-designed tools. Use when building MCP servers to integrate external APIs or services, whether in Python (FastMCP) or Node/TypeScript (MCP SDK).', descriptionZh: '创建高质量 MCP（模型上下文协议）服务器——Python(FastMCP) 或 Node/TS(MCP SDK)，让大模型通过工具接入外部服务。', repo: 'anthropics/skills', path: 'skills/mcp-builder', ref: 'main' },
  { id: 'pdf', name: 'pdf', nameZh: 'PDF 处理', description: 'Use this skill whenever the user wants to do anything with PDF files. This includes reading or extracting text/tables from PDFs, combining or merging multiple PDFs into one, splitting PDFs apart, rotating pages, adding watermarks, creating new PDFs, filling PDF forms, encrypting/decrypting PDFs, extracting images, and OCR on scanned PDFs to make them searchable. If the user mentions a .pdf file or asks to produce one, use this skill.', descriptionZh: '处理 PDF 文件：提取文字与表格、合并或拆分、旋转页面、加水印、创建新 PDF、填写表单、加密/解密、提取图片、扫描件 OCR。', repo: 'anthropics/skills', path: 'skills/pdf', ref: 'main' },
  { id: 'pptx', name: 'pptx', nameZh: 'PowerPoint 演示文稿', description: 'Use this skill any time a .pptx or .potx file is involved in any way — as input, output, or both. This includes: creating slide decks, pitch decks, or presentations; reading, parsing, or extracting text from any .pptx or .potx file (even if the extracted content will be used elsewhere, like in an email or summary); editing, modifying, or updating existing presentations; combining or splitting slide files; working with templates (.potx), layouts, speaker notes, or comments. Trigger whenever the user mentions \\"deck,\\" \\"slides,\\" \\"presentation,\\" or references a .pptx or .potx filename, regardless of what they plan to do with the content afterward. If a .pptx or .potx file needs to be opened, created, or touched, use this skill.', descriptionZh: '创建与编辑 .pptx/.potx 演示文稿：幻灯片、模板、版式、演讲备注、批注，以及合并与拆分幻灯片文件。', repo: 'anthropics/skills', path: 'skills/pptx', ref: 'main' },
  { id: 'skill-creator', name: 'skill-creator', nameZh: '技能创作', description: "Create new skills, modify and improve existing skills, and measure skill performance. Use when users want to create a skill from scratch, edit, or optimize an existing skill, run evals to test a skill, benchmark skill performance with variance analysis, or optimize a skill's description for better triggering accuracy.", descriptionZh: '从零创建新技能、修改与优化现有技能、运行评测测试技能效果、基准对比，以及优化技能描述提高触发准确率。', repo: 'anthropics/skills', path: 'skills/skill-creator', ref: 'main' },
  { id: 'slack-gif-creator', name: 'slack-gif-creator', nameZh: 'Slack GIF 制作', description: 'Knowledge and utilities for creating animated GIFs optimized for Slack. Provides constraints, validation tools, and animation concepts. Use when users request animated GIFs for Slack like "make me a GIF of X doing Y for Slack.', descriptionZh: '制作针对 Slack 优化的动图 GIF：尺寸约束、校验工具与动画概念。', repo: 'anthropics/skills', path: 'skills/slack-gif-creator', ref: 'main' },
  { id: 'theme-factory', name: 'theme-factory', nameZh: '主题样式工厂', description: 'Toolkit for styling artifacts with a theme. These artifacts can be slides, docs, reportings, HTML landing pages, etc. There are 10 pre-set themes with colors/fonts that you can apply to any artifact that has been creating, or can generate a new theme on-the-fly.', descriptionZh: '为作品（幻灯片、文档、报告、HTML 落地页）套用主题：10 套预设配色字体主题，也可即时生成新主题。', repo: 'anthropics/skills', path: 'skills/theme-factory', ref: 'main' },
  { id: 'web-artifacts-builder', name: 'web-artifacts-builder', nameZh: 'HTML 工件构建', description: 'Suite of tools for creating elaborate, multi-component claude.ai HTML artifacts using modern frontend web technologies (React, Tailwind CSS, shadcn/ui). Use for complex artifacts requiring state management, routing, or shadcn/ui components - not for simple single-file HTML/JSX artifacts.', descriptionZh: '用现代前端技术（React、Tailwind、shadcn/ui）构建复杂多组件 HTML 工件；需要状态管理、路由或组件库时使用。', repo: 'anthropics/skills', path: 'skills/web-artifacts-builder', ref: 'main' },
  { id: 'webapp-testing', name: 'webapp-testing', nameZh: '网页应用测试', description: 'Toolkit for interacting with and testing local web applications using Playwright. Supports verifying frontend functionality, debugging UI behavior, capturing browser screenshots, and viewing browser logs.', descriptionZh: '用 Playwright 与本地网页应用交互测试：验证前端功能、调试 UI 行为、截取浏览器截图、查看浏览器日志。', repo: 'anthropics/skills', path: 'skills/webapp-testing', ref: 'main' },
  { id: 'xlsx', name: 'xlsx', nameZh: 'Excel 表格处理', description: 'Use this skill any time a spreadsheet file is the primary input or output. This means any task where the user wants to: open, read, edit, or fix an existing .xlsx, .xlsm, .xltx, .csv, or .tsv file (e.g., adding columns, computing formulas, formatting, charting, cleaning messy data); create a new spreadsheet from scratch or from other data sources; or convert between tabular file formats. Trigger especially when the user references a spreadsheet file by name or path — even casually (like \\"the xlsx in my downloads\\") — and wants something done to it or produced from it. Also trigger for cleaning or restructuring messy tabular data files (malformed rows, misplaced headers, junk data) into proper spreadsheets. The deliverable must be a spreadsheet file. Do NOT trigger when the primary deliverable is a Word document, HTML report, standalone Python script, database pipeline, or Google Sheets API integration, even if tabular data is involved.', descriptionZh: '处理电子表格：打开、读取、编辑、修复 .xlsx/.xlsm/.xltx/.csv/.tsv；新建表格、公式计算、格式化、图表、清洗脏数据。', repo: 'anthropics/skills', path: 'skills/xlsx', ref: 'main' },
  { id: 'brainstorming', name: 'brainstorming', nameZh: '头脑风暴', description: 'You MUST use this before any creative work - creating features, building components, adding functionality, or modifying behavior. Explores user intent, requirements and design before implementation.', descriptionZh: '任何创造性工作前必须使用：创建功能、构建组件、添加功能或修改行为前，先探索用户意图、需求与设计再实现。', repo: 'obra/superpowers', path: 'skills/brainstorming', ref: 'main' },
  { id: 'dispatching-parallel-agents', name: 'dispatching-parallel-agents', nameZh: '并行代理调度', description: 'Use when facing 2+ independent tasks that can be worked on without shared state or sequential dependencies', descriptionZh: '面对 2 个及以上无共享状态、无顺序依赖的独立任务时，并行派发子代理分别处理。', repo: 'obra/superpowers', path: 'skills/dispatching-parallel-agents', ref: 'main' },
  { id: 'executing-plans', name: 'executing-plans', nameZh: '执行计划', description: 'Use when you have a written implementation plan to execute in a separate session with review checkpoints', descriptionZh: '拿到书面实现计划、需要在独立会话中按检查点执行时使用。', repo: 'obra/superpowers', path: 'skills/executing-plans', ref: 'main' },
  { id: 'finishing-a-development-branch', name: 'finishing-a-development-branch', nameZh: '完成开发分支', description: 'Use when implementation is complete, all tests pass, and you need to decide how to integrate the work', descriptionZh: '实现完成、测试全部通过后，需要决定如何集成工作成果时使用。', repo: 'obra/superpowers', path: 'skills/finishing-a-development-branch', ref: 'main' },
  { id: 'receiving-code-review', name: 'receiving-code-review', nameZh: '接收代码评审', description: 'Use when receiving code review feedback, before implementing suggestions, especially if feedback seems unclear or technically questionable - requires technical rigor and verification, not performative agreement or blind implementation', descriptionZh: '收到代码评审意见后、实现建议之前使用：要求技术严谨性与验证，而非表演性同意或盲从实现。', repo: 'obra/superpowers', path: 'skills/receiving-code-review', ref: 'main' },
  { id: 'requesting-code-review', name: 'requesting-code-review', nameZh: '请求代码评审', description: 'Use when completing tasks, implementing major features, or before merging to verify work meets requirements', descriptionZh: '完成任务、实现主要功能或合并之前，验证工作符合需求时使用。', repo: 'obra/superpowers', path: 'skills/requesting-code-review', ref: 'main' },
  { id: 'subagent-driven-development', name: 'subagent-driven-development', nameZh: '子代理驱动开发', description: 'Use when executing implementation plans with independent tasks in the current session', descriptionZh: '在当前会话中执行含独立任务的实现计划时使用，把任务分派给子代理并行推进。', repo: 'obra/superpowers', path: 'skills/subagent-driven-development', ref: 'main' },
  { id: 'systematic-debugging', name: 'systematic-debugging', nameZh: '系统化调试', description: 'Use when encountering any bug, test failure, or unexpected behavior, before proposing fixes', descriptionZh: '遇到任何 bug、测试失败或异常行为时、提出修复方案之前使用，系统化定位根因。', repo: 'obra/superpowers', path: 'skills/systematic-debugging', ref: 'main' },
  { id: 'test-driven-development', name: 'test-driven-development', nameZh: '测试驱动开发', description: 'Use when implementing any feature or bugfix, before writing implementation code', descriptionZh: '实现任何功能或修复 bug 之前、编写实现代码之前使用，先写测试。', repo: 'obra/superpowers', path: 'skills/test-driven-development', ref: 'main' },
  { id: 'using-git-worktrees', name: 'using-git-worktrees', nameZh: 'Git Worktree 使用', description: 'Use when starting feature work that needs isolation from current workspace or before executing implementation plans - ensures an isolated workspace exists via native tools or git worktree fallback', descriptionZh: '开始需要与当前工作区隔离的功能开发时使用，确保存在隔离工作区（原生工具或 git worktree 兜底）。', repo: 'obra/superpowers', path: 'skills/using-git-worktrees', ref: 'main' },
  { id: 'using-superpowers', name: 'using-superpowers', nameZh: '使用 Superpowers', description: 'Use when starting any conversation - establishes how to find and use skills, requiring skill invocation before ANY response including clarifying questions', descriptionZh: '任何对话开始时使用：建立如何查找与使用技能，要求在任何回复（包括澄清问题）之前先调用相关技能。', repo: 'obra/superpowers', path: 'skills/using-superpowers', ref: 'main' },
  { id: 'verification-before-completion', name: 'verification-before-completion', nameZh: '完成前验证', description: 'Use when about to claim work is complete, fixed, or passing, before committing or creating PRs - requires running verification commands and confirming output before making any success claims; evidence before assertions always', descriptionZh: '宣称工作完成、已修复或通过之前使用：先运行验证命令并确认输出，任何成功断言前必须有证据。', repo: 'obra/superpowers', path: 'skills/verification-before-completion', ref: 'main' },
  { id: 'writing-plans', name: 'writing-plans', nameZh: '编写计划', description: 'Use when you have a spec or requirements for a multi-step task, before touching code', descriptionZh: '有规格或需求、任务包含多个步骤、动手写代码之前使用，先编写实现计划。', repo: 'obra/superpowers', path: 'skills/writing-plans', ref: 'main' },
  { id: 'writing-skills', name: 'writing-skills', nameZh: '编写技能', description: 'Use when creating new skills, editing existing skills, or verifying skills work before deployment', descriptionZh: '创建新技能、编辑现有技能或在部署前验证技能是否可用时使用。', repo: 'obra/superpowers', path: 'skills/writing-skills', ref: 'main' },
]
